spring.application.name=production-ready-features

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/production-ready-features
spring.datasource.username=root
spring.datasource.password=Swift@5140

server.port = 8090
employeeRestClient.base.url = http://localhost:8080/
